---
- name: Delete Application VPC & Associated Components
  hosts: localhost
  tasks:
    - name: Get VPC Facts
      ec2_vpc_net_facts:
        filters:
          "tag:Name": "{{ app_prefix }}-vpc"
        region: "{{ aws_region }}"
      register: ec2_vpc_net_facts_results

    - name: Debug ec2_vpc_net_facts_results
      debug:
        var: ec2_vpc_net_facts_results
        verbosity: 2

    - name: Get VPC Security Group Facts
      ec2_group_facts:
        filters:
          vpc-id: "{{ ec2_vpc_net_facts_results.vpcs[0].id }}"
        region: "{{ aws_region }}"
      register: ec2_group_facts_results

    - name: Debug ec2_group_facts_results
      debug:
        var: ec2_group_facts_results
        verbosity: 2

    # Can't delete the default security group, so skip

    - name: Delete VPC Security Groups
      ec2_group:
        group_id: "{{ item.group_id }}"
        region: "{{ aws_region }}"
        state: absent
      when: item.group_name != "default"
      with_items:
        - "{{ ec2_group_facts_results.security_groups }}"

    - name: Get VPC Subnet Facts
      ec2_vpc_subnet_facts:
        filters:
          vpc-id: "{{ ec2_vpc_net_facts_results.vpcs[0].id }}"
        region: "{{ aws_region }}"
      register: ec2_vpc_subnet_facts_results

    - name: Debug ec2_vpc_subnet_facts_results
      debug:
        var: ec2_vpc_subnet_facts_results
        verbosity: 2

    - name: Delete VPC Subnets
      ec2_vpc_subnet:
        cidr: "{{ item.cidr_block }}"
        region: "{{ aws_region }}"
        state: absent
        vpc_id: "{{ ec2_vpc_net_facts_results.vpcs[0].id }}"
      with_items:
        - "{{ ec2_vpc_subnet_facts_results.subnets }}"

    - name: Delete VPC IGW
      ec2_vpc_igw:
        region: "{{ aws_region }}"
        state: absent
        vpc_id: "{{ ec2_vpc_net_facts_results.vpcs[0].id }}"

    - name: Delete VPC
      ec2_vpc_net:
        cidr_block: "10.250.0.0/16"
        name: "{{ ec2_vpc_net_facts_results.vpcs[0].tags.Name }}"
        region: "{{ aws_region }}"
        state: absent
